# Generated by Django 4.1.7 on 2023-03-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slag',
            new_name='slug',
        ),
    ]
